# Generated by Django 3.2.3 on 2021-05-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_url',
            new_name='url',
        ),
    ]
